steps:
  # Step 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/\/my-apps/micro-api:\'
      - '.'

  # Step 2: Push Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/\/my-apps/micro-api:\'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'micro-api-service'
      - '--image=us-central1-docker.pkg.dev/\/my-apps/micro-api:\'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'

images:
  - 'us-central1-docker.pkg.dev/\/my-apps/micro-api:\'

options:
  logging: CLOUD_LOGGING_ONLY
